/* Supabase 連線競技場：真人配對、伺服器回合計算、雙方同步戰報。 */
(function(){
'use strict';
let pc=null,pu=null,pTimer=null,pState={kind:'idle'},pBusy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ready=()=>window.MARKET_CONFIG&&window.supabase&&window.supabase.createClient;
function panel(){let p=document.getElementById('pvp-panel');if(p)return p;p=document.createElement('div');p.id='pvp-panel';p.innerHTML='<div class="pvp-window"><button class="pvp-x" onclick="pvpClose()">×</button><header><b>⚔ 連線競技場</b><small id="pvp-account"></small></header><div id="pvp-body"></div></div>';document.body.appendChild(p);let st=document.createElement('style');st.textContent=`#pvp-panel{display:none;position:fixed;inset:0;z-index:14000;background:#020617e8;align-items:center;justify-content:center;padding:12px}.pvp-window{position:relative;width:min(920px,98vw);max-height:94vh;overflow:auto;color:#f8fafc;background:radial-gradient(circle at 50% 0,#451a03,#111827 48%);border:2px solid #f59e0b;border-radius:16px;padding:20px;box-shadow:0 0 45px #dc262666}.pvp-window header b{font-size:26px;color:#fde68a}.pvp-window header small{display:block;color:#94a3b8;margin-top:3px}.pvp-x{position:absolute;right:12px;top:8px;font-size:30px;color:#fff}.pvp-card{background:#0f172ae6;border:1px solid #92400e;border-radius:11px;padding:14px;margin:10px 0}.pvp-actions{display:flex;gap:10px;justify-content:center;flex-wrap:wrap;margin:15px 0}.pvp-actions button,.pvp-window button.pvp-btn{padding:10px 20px;border:1px solid #f59e0b;border-radius:9px;background:#9a3412;color:#fff7ed;font-weight:bold}.pvp-duel{display:grid;grid-template-columns:1fr 90px 1fr;gap:14px;align-items:center}.pvp-fighter{background:#111827;border:1px solid #475569;border-radius:12px;padding:14px}.pvp-fighter.mine{border-color:#38bdf8;box-shadow:0 0 14px #0ea5e944}.pvp-fighter h3{font-size:21px;color:#fde68a}.pvp-hp{height:20px;background:#334155;border-radius:10px;overflow:hidden;margin:8px 0}.pvp-hp>i{display:block;height:100%;background:linear-gradient(90deg,#991b1b,#ef4444);transition:width .35s}.pvp-vs{text-align:center;font-size:30px;font-weight:bold;color:#fb923c}.pvp-log{max-height:280px;overflow:auto;background:#020617;border:1px solid #334155;border-radius:10px;padding:9px}.pvp-log div{padding:6px 8px;border-bottom:1px solid #1e293b}.pvp-result{text-align:center;font-size:25px;font-weight:bold;padding:16px;color:#facc15}@media(max-width:650px){.pvp-duel{grid-template-columns:1fr}.pvp-vs{font-size:20px}.pvp-window{padding:14px}}`;document.head.appendChild(st);return p;}
function body(){return document.getElementById('pvp-body');}
function note(t,c='#fbbf24'){body().innerHTML=`<div class="pvp-card" style="text-align:center;color:${c}">${t}</div>`;}
async function init(){if(!ready())throw new Error('Supabase 尚未設定。');if(!pc)pc=window.supabase.createClient(MARKET_CONFIG.url,MARKET_CONFIG.anonKey,{auth:{persistSession:true,autoRefreshToken:true}});let {data:{session}}=await pc.auth.getSession();if(!session){let r=await pc.auth.signInAnonymously();if(r.error)throw r.error;session=r.data.session;}pu=session.user;let n=(window.player&&player.name)||'冒險者';let e=await pc.rpc('market_ensure_profile',{p_name:n});if(e.error)throw e.error;let id=await pc.rpc('player_my_identity');let tag=!id.error&&id.data&&id.data.player_tag;document.getElementById('pvp-account').textContent=`${n}｜${tag?'@'+tag:'請先設定玩家 ID'}`;}
function snapshot(){if(typeof calcStats==='function')calcStats();let d=player.d||{},lv=Number(player.lv||1),atk=Math.max(Number(d.meleeDmg||0),Number(d.rangedDmg||0),Number(d.magicDmg||0))+Number(d.extraDmg||0)+lv*8,def=Math.max(0,-Number(d.ac||0))*2+Number(d.dr||0)*15+Number(d.mr||0)*.25,crit=Math.max(Number(d.meleeCrit||0),Number(d.rangedCrit||0),Number(d.magicCrit||0)),speed=1/Math.max(.4,Number(d.aspd||1));return{lv:Math.round(lv),class:player.cls||'冒險者',max_hp:Math.round(Math.max(100,Number(player.mhp||player.hp||100))),atk:Math.round(atk),def:Math.round(def),crit:Math.round(crit*10)/10,speed:Math.round(speed*100)/100};}
function recordHtml(r={}){return `<div class="pvp-card" style="display:flex;justify-content:space-around;gap:8px;flex-wrap:wrap"><b>競技積分 ${Number(r.rating||1000)}</b><span>勝 ${Number(r.wins||0)}</span><span>敗 ${Number(r.losses||0)}</span><span>和 ${Number(r.draws||0)}</span></div>`;}
function renderIdle(s){body().innerHTML=`<div class="pvp-card"><h2 style="font-size:22px;color:#fdba74">真人連線自動 PK</h2><p>系統會尋找另一位正在排隊的玩家。配對後，雙方會看到同一份 HP、回合與戰報；戰鬥由伺服器計算直到分出勝負。</p><small style="color:#94a3b8">角色的 HP、攻擊、防禦、爆擊與攻速會轉換成競技場能力。勝利 +15 分，失敗 -10 分，平手 +2 分。</small></div>${recordHtml(s)}<div class="pvp-actions"><button onclick="pvpStart()">開始配對</button></div>`;}
function renderQueue(s){body().innerHTML=`${recordHtml(s)}<div class="pvp-card" style="text-align:center"><div style="font-size:46px">⚔</div><h2 style="font-size:22px;color:#fde68a">尋找對手中…</h2><p>${esc(s.message||'等待另一位玩家')}</p><small style="color:#94a3b8">請保持此視窗開啟，配對成功會自動進入戰鬥。</small></div><div class="pvp-actions"><button onclick="pvpCancel()">取消配對</button></div>`;}
function fighter(x,side,mine){let st=x.stats||{},hp=Number(x.hp||0),max=Number(st.max_hp||1),pct=Math.max(0,Math.min(100,hp/max*100));return `<div class="pvp-fighter ${mine===side?'mine':''}"><h3>${mine===side?'⭐ ':''}${esc(x.name)}</h3><small>${x.tag?'@'+esc(x.tag)+'｜':''}Lv.${st.lv||1} ${esc(st.class||'')}</small><div class="pvp-hp"><i style="width:${pct}%"></i></div><b>HP ${hp.toLocaleString()} / ${max.toLocaleString()}</b><small style="display:block;color:#94a3b8;margin-top:6px">攻擊 ${st.atk}｜防禦 ${st.def}｜爆擊 ${st.crit}%｜攻速 ${st.speed}</small></div>`;}
function renderMatch(s){let logs=(s.log||[]).slice(-14).reverse().map(x=>`<div><b style="color:#fde68a">第 ${x.round} 回合</b>　${esc(s.player1.name)} 造成 <span style="color:#fb923c">${Number(x.d1).toLocaleString()}</span>${x.c1?'（爆擊）':''}，${esc(s.player2.name)} 造成 <span style="color:#60a5fa">${Number(x.d2).toLocaleString()}</span>${x.c2?'（爆擊）':''}</div>`).join('');let done=s.status==='finished',won=s.winner_id&&s.winner_id===pu.id,draw=done&&!s.winner_id;body().innerHTML=`<div class="pvp-duel">${fighter(s.player1,1,s.my_side)}<div class="pvp-vs">VS<br><small>回合 ${s.round}</small></div>${fighter(s.player2,2,s.my_side)}</div>${done?`<div class="pvp-result" style="color:${draw?'#cbd5e1':won?'#86efac':'#fca5a5'}">${draw?'平手':won?'🏆 勝利':'戰敗'}<br><small>${esc(s.result_text||'戰鬥結束')}</small></div>`:'<div class="pvp-card" style="text-align:center;color:#93c5fd">雙方正在自動交戰，戰況由伺服器同步…</div>'}<div class="pvp-log">${logs||'<div>戰鬥即將開始…</div>'}</div>${done?recordHtml(s.record):''}<div class="pvp-actions">${done?'<button onclick="pvpStart()">再次配對</button>':'<button onclick="pvpForfeit()">投降</button>'}</div>`;}
function render(s){pState=s||{kind:'idle'};if(pState.kind==='queued')renderQueue(pState);else if(pState.kind==='match')renderMatch(pState);else renderIdle(pState);}
function schedule(){clearTimeout(pTimer);if(document.getElementById('pvp-panel')?.style.display!=='flex')return;if(pState.kind==='queued'||(pState.kind==='match'&&pState.status==='active'))pTimer=setTimeout(step,900);}
async function step(){if(pBusy)return schedule();pBusy=true;try{let r=pState.kind==='match'?await pc.rpc('pvp_tick',{p_match:pState.id}):await pc.rpc('pvp_poll');if(r.error)throw r.error;render(r.data);}catch(e){note(esc(e.message),'#fca5a5');}finally{pBusy=false;schedule();}}
window.pvpOpen=async()=>{let p=panel();p.style.display='flex';note('正在連線競技場…','#93c5fd');try{await init();let r=await pc.rpc('pvp_poll');if(r.error)throw r.error;render(r.data);schedule();}catch(e){note(`${esc(e.message)}<br><br>請先到 Supabase SQL Editor 執行 <b>supabase-pvp.sql</b>。`,'#fca5a5');}};
window.pvpClose=async()=>{clearTimeout(pTimer);if(pState.kind==='queued'&&pc)await pc.rpc('pvp_cancel_queue');let p=document.getElementById('pvp-panel');if(p)p.style.display='none';};
window.pvpStart=async()=>{if(pBusy)return;pBusy=true;note('正在加入配對…','#93c5fd');try{let r=await pc.rpc('pvp_join_queue',{p_snapshot:snapshot()});if(r.error)throw r.error;render(r.data);}catch(e){note(esc(e.message),'#fca5a5');}finally{pBusy=false;schedule();}};
window.pvpCancel=async()=>{clearTimeout(pTimer);let r=await pc.rpc('pvp_cancel_queue');if(r.error)return alert(r.error.message);pState={kind:'idle'};let s=await pc.rpc('pvp_poll');render(s.data);};
window.pvpForfeit=async()=>{if(!confirm('確定要投降並判定本場失敗嗎？'))return;let r=await pc.rpc('pvp_forfeit',{p_match:pState.id});if(r.error)return alert(r.error.message);render(r.data);};
})();

/* PvP visual battle layer: turns the synchronized combat result into an animated scene. */
(function(){
'use strict';
let lastKey='', observer=null;
const classAvatar={royal:'王子',knight:'男騎士',elf:'男妖精',mage:'男法師',darkelf:'男黑暗妖精',dragonknight:'男龍騎士',illusion:'男幻術士',warrior:'男戰士','王族':'王子','騎士':'男騎士','妖精':'男妖精','法師':'男法師','黑暗妖精':'男黑暗妖精','龍騎士':'男龍騎士','幻術士':'男幻術士','戰士':'男戰士'};
const clsWeapon={elf:'bow',mage:'wand',darkelf:'dagger',illusion:'wand',warrior:'sword2'};
function css(){if(document.getElementById('pvp-visual-css'))return;let s=document.createElement('style');s.id='pvp-visual-css';s.textContent=`
.pvp-arena{height:330px;position:relative;overflow:hidden;margin:12px 0 15px;border:2px solid #b45309;border-radius:15px;background:linear-gradient(#02061744,#02061799),url('assets/area/冥法軍訓練場.jpg') center/cover;box-shadow:inset 0 -55px 60px #020617cc,0 0 24px #f59e0b33}
.pvp-arena:after{content:'';position:absolute;left:5%;right:5%;bottom:28px;height:34px;border-radius:50%;background:#02061766;filter:blur(13px)}
.pvp-round{position:absolute;z-index:8;left:50%;top:12px;transform:translateX(-50%);padding:6px 17px;border:1px solid #f59e0b;border-radius:20px;background:#020617d9;color:#fde68a;font-weight:900;box-shadow:0 0 18px #f59e0b77}
.pvp-actor{position:absolute;z-index:4;bottom:32px;width:40%;height:235px;display:flex;align-items:flex-end;justify-content:center;transition:filter .2s,opacity .3s}.pvp-actor.a{left:2%}.pvp-actor.b{right:2%}
.pvp-sprite-wrap{position:relative;height:190px;width:190px;display:flex;align-items:flex-end;justify-content:center;filter:drop-shadow(0 9px 6px #000b)}
.pvp-sprite{max-width:180px;max-height:190px;image-rendering:auto;object-fit:contain;transform-origin:50% 85%}.pvp-actor.b .pvp-sprite{transform:scaleX(-1)}
.pvp-name{position:absolute;z-index:7;top:48px;width:38%;text-align:center;color:#fff;font-size:17px;font-weight:900;text-shadow:0 2px 4px #000}.pvp-name.a{left:3%}.pvp-name.b{right:3%}.pvp-name small{display:block;color:#cbd5e1;font-size:12px}
.pvp-stage-hp{height:12px;margin:5px auto 0;max-width:220px;background:#111827;border:1px solid #f8fafc99;border-radius:8px;overflow:hidden}.pvp-stage-hp i{display:block;height:100%;background:linear-gradient(90deg,#b91c1c,#ef4444,#fb7185);transition:width .3s}
.pvp-damage{position:absolute;z-index:12;left:50%;top:46px;transform:translateX(-50%);font-size:34px;font-weight:1000;color:#facc15;-webkit-text-stroke:1px #7f1d1d;text-shadow:0 4px 8px #000;opacity:0;pointer-events:none}.pvp-damage.crit{font-size:44px;color:#ff3535;text-shadow:0 0 14px #ef4444,0 4px 8px #000}
.pvp-actor.attack-a{animation:pvpLungeA .42s ease}.pvp-actor.attack-b{animation:pvpLungeB .42s ease}.pvp-actor.hurt{animation:pvpHurt .34s ease;filter:brightness(2) sepia(1) hue-rotate(300deg) drop-shadow(0 0 14px #ef4444)}.pvp-damage.show{animation:pvpFloat .75s ease-out}.pvp-actor.dead{animation:pvpFall .8s forwards;filter:grayscale(1) brightness(.55)}
.pvp-impact{position:absolute;z-index:6;left:50%;bottom:105px;width:90px;height:90px;border-radius:50%;opacity:0;background:radial-gradient(circle,#fff 0,#facc15 14%,#ef4444aa 32%,transparent 67%)}.pvp-impact.show{animation:pvpImpact .35s ease-out}
@keyframes pvpLungeA{0%,100%{transform:translateX(0)}45%{transform:translateX(115px) scale(1.09)}}@keyframes pvpLungeB{0%,100%{transform:translateX(0)}45%{transform:translateX(-115px) scale(1.09)}}@keyframes pvpHurt{0%,100%{transform:translateX(0)}25%{transform:translateX(-13px)}50%{transform:translateX(13px)}75%{transform:translateX(-8px)}}@keyframes pvpFloat{0%{opacity:0;transform:translate(-50%,18px) scale(.6)}20%{opacity:1;transform:translate(-50%,0) scale(1.18)}100%{opacity:0;transform:translate(-50%,-70px) scale(.95)}}@keyframes pvpImpact{0%{opacity:1;transform:scale(.25)}100%{opacity:0;transform:scale(1.8)}}@keyframes pvpFall{100%{transform:rotate(78deg) translate(35px,28px);opacity:.6}}
@media(max-width:650px){.pvp-arena{height:265px}.pvp-sprite-wrap{width:125px;height:145px}.pvp-sprite{max-width:125px;max-height:145px}.pvp-name{top:42px;font-size:14px}.pvp-actor{height:175px}.pvp-actor.attack-a{animation-name:pvpLungeAm}.pvp-actor.attack-b{animation-name:pvpLungeBm}@keyframes pvpLungeAm{45%{transform:translateX(48px) scale(1.08)}}@keyframes pvpLungeBm{45%{transform:translateX(-48px) scale(1.08)}}}
`;document.head.appendChild(s)}
function text(el){return (el&&el.textContent||'').trim()}
function parseFighter(el,mine){let title=text(el.querySelector('h3')).replace(/^你\s*/,'')||'冒險者',sub=text(el.querySelector('small')),hpText=text(el.querySelector('b')),nums=hpText.match(/[\d,]+/g)||['0','1'],hp=Number(nums[0].replace(/,/g,''))||0,max=Number((nums[1]||'1').replace(/,/g,''))||1,cls=(sub.match(/Lv\.\d+\s+(.+)$/)||[])[1]||'knight',key=String(cls).trim(),avatar=mine&&window.player&&player.avatar?player.avatar:(classAvatar[key]||classAvatar[key.toLowerCase()]||'男騎士'),weapon=clsWeapon[key.toLowerCase()]||'sword1';return{title,sub,hp,max,avatar,weapon}}
function path(f,act,n=0){return `assets/classanim/${encodeURIComponent(f.avatar)}/${f.weapon}_${act}_${n}.png`}
function actor(f,side){let pct=Math.max(0,Math.min(100,f.hp/f.max*100));return `<div class="pvp-name ${side}">${f.title}<small>${f.sub}</small><div class="pvp-stage-hp"><i style="width:${pct}%"></i></div></div><div class="pvp-actor ${side}${f.hp<=0?' dead':''}" data-avatar="${f.avatar}" data-weapon="${f.weapon}"><div class="pvp-sprite-wrap"><img class="pvp-sprite" src="${path(f,'idle')}" onerror="this.onerror=null;this.src='assets/classanim/%E7%94%B7%E9%A8%8E%E5%A3%AB/sword1_idle_0.png'"><b class="pvp-damage"></b></div></div>`}
function build(body){let duel=body.querySelector('.pvp-duel');if(!duel||body.querySelector('.pvp-arena'))return;let cards=duel.querySelectorAll('.pvp-fighter');if(cards.length<2)return;let a=parseFighter(cards[0],cards[0].classList.contains('mine')),b=parseFighter(cards[1],cards[1].classList.contains('mine')),round=(text(duel.querySelector('.pvp-vs')).match(/\d+/)||['0'])[0],stage=document.createElement('div');stage.className='pvp-arena';stage.innerHTML=`<div class="pvp-round">第 ${round} 回合</div>${actor(a,'a')}${actor(b,'b')}<i class="pvp-impact"></i>`;duel.before(stage);let row=body.querySelector('.pvp-log div'),spans=row?row.querySelectorAll('span'):[],key=`${text(row)}|${a.hp}|${b.hp}`;if(row&&key!==lastKey){lastKey=key;let d1=spans[0]?Number(text(spans[0]).replace(/,/g,'')):0,d2=spans[1]?Number(text(spans[1]).replace(/,/g,'')):0,crit=/爆擊/.test(text(row));setTimeout(()=>strike(stage,'a','b',d1,crit),80);setTimeout(()=>strike(stage,'b','a',d2,crit),500)}}
function frames(actor,act,count,done){let img=actor.querySelector('.pvp-sprite'),av=actor.dataset.avatar,w=actor.dataset.weapon,i=0,t=setInterval(()=>{img.src=`assets/classanim/${encodeURIComponent(av)}/${w}_${act}_${i++}.png`;if(i>=count){clearInterval(t);setTimeout(()=>{img.src=`assets/classanim/${encodeURIComponent(av)}/${w}_idle_0.png`;done&&done()},35)}},55)}
function strike(stage,from,to,damage,crit){if(!damage)return;let a=stage.querySelector(`.pvp-actor.${from}`),b=stage.querySelector(`.pvp-actor.${to}`),n=b.querySelector('.pvp-damage'),impact=stage.querySelector('.pvp-impact');if(!a||!b)return;a.classList.add(`attack-${from}`);frames(a,'attack',6);setTimeout(()=>{b.classList.add('hurt');frames(b,'hurt',2);n.textContent=`-${damage.toLocaleString()}${crit?' 爆擊！':''}`;n.className=`pvp-damage show${crit?' crit':''}`;impact.classList.add('show');setTimeout(()=>{a.classList.remove(`attack-${from}`);b.classList.remove('hurt');impact.classList.remove('show')},430)},185)}
function watch(){css();let b=document.getElementById('pvp-body');if(!b||b.dataset.visualWatch)return;b.dataset.visualWatch='1';observer=new MutationObserver(()=>build(b));observer.observe(b,{childList:true,subtree:true});build(b)}
new MutationObserver(()=>watch()).observe(document.documentElement,{childList:true,subtree:true});if(document.readyState!=='loading')watch();else document.addEventListener('DOMContentLoaded',watch);
})();
