/* Supabase 玩家交易所：匿名帳號、雲端錢包、掛賣、購買、下架、領取。 */
(function(){
'use strict';
let client=null,user=null,busy=false,tab='browse';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n||0).toLocaleString();
const configured=()=>window.MARKET_CONFIG&&/^https:\/\/.+\.supabase\.co$/.test(MARKET_CONFIG.url||'')&&!String(MARKET_CONFIG.anonKey||'').startsWith('YOUR_');
function panel(){let p=document.getElementById('market-panel');if(p)return p;p=document.createElement('div');p.id='market-panel';p.style.cssText='position:fixed;inset:0;z-index:12500;background:#000c;display:none;align-items:center;justify-content:center;padding:14px';p.innerHTML='<div style="width:min(1050px,98vw);height:min(850px,94vh);background:#101827;border:2px solid #38bdf8;border-radius:14px;display:flex;flex-direction:column;color:#e5e7eb;overflow:hidden"><header style="display:flex;align-items:center;justify-content:space-between;padding:14px 18px;background:#172554;border-bottom:1px solid #475569"><div><b style="font-size:25px;color:#7dd3fc">⚖ 玩家交易所</b><small id="market-account" style="display:block;color:#94a3b8"></small></div><button onclick="marketClose()" style="padding:9px 14px">✕ 關閉</button></header><nav id="market-tabs" style="display:flex;gap:7px;flex-wrap:wrap;padding:10px 14px;border-bottom:1px solid #334155"></nav><main id="market-body" style="padding:14px;overflow:auto;flex:1"></main></div>';document.body.appendChild(p);return p;}
function note(text,color='#fbbf24'){document.getElementById('market-body').innerHTML=`<div style="padding:22px;border:1px solid #475569;border-radius:10px;color:${color};line-height:1.8">${text}</div>`;}
async function init(){
 if(!configured())throw new Error('尚未設定 Supabase。請依照「交易所設定教學.md」填寫 supabase-config.js。');
 if(!window.supabase||!window.supabase.createClient)throw new Error('Supabase 程式庫載入失敗，請確認網路連線。');
 if(!client)client=window.supabase.createClient(MARKET_CONFIG.url,MARKET_CONFIG.anonKey,{auth:{persistSession:true,autoRefreshToken:true}});
 let {data:{session}}=await client.auth.getSession();if(!session){const r=await client.auth.signInAnonymously();if(r.error)throw r.error;session=r.data.session;}
 user=session.user;const n=(window.player&&player.name)||'冒險者';const r=await client.rpc('market_ensure_profile',{p_name:n});if(r.error)throw r.error;
 document.getElementById('market-account').textContent=`${n}｜線上編號 ${user.id.slice(0,8)}`;
}
window.marketOpen=async function(){const p=panel();p.style.display='flex';note('正在連線交易所…','#93c5fd');try{await init();renderTabs();await show(tab);}catch(e){note(`${esc(e.message)}<br><br>設定步驟：建立 Supabase 專案 → 開啟匿名登入 → 執行 supabase-market.sql → 填寫 supabase-config.js。`,'#fca5a5');}};
window.marketClose=function(){const p=document.getElementById('market-panel');if(p)p.style.display='none';};
function renderTabs(){const defs=[['browse','市場'],['sell','我要掛賣'],['mine','我的掛賣'],['delivery','待領取'],['wallet','交易錢包']];document.getElementById('market-tabs').innerHTML=defs.map(x=>`<button onclick="marketTab('${x[0]}')" style="padding:9px 15px;border-color:${tab===x[0]?'#38bdf8':'#475569'};color:${tab===x[0]?'#7dd3fc':'#cbd5e1'}">${x[1]}</button>`).join('');}
window.marketTab=async function(k){if(busy)return;tab=k;renderTabs();await show(k);};
async function show(k){if(!client)return;if(k==='browse')return browse();if(k==='sell')return sell();if(k==='mine')return mine();if(k==='delivery')return deliveries();return wallet();}
function itemTitle(it){const d=DB.items[it.id]||{};return `${it.en>0?'+'+it.en+' ':''}${it.bless===true?'祝福的 ':''}${d.n||it.id}${it.seteff?'【'+it.seteff+'】':''}${it.fourEle?`【${it.fourEle}附魔${it.fourEleLv||1}階】`:''}`;}
async function profile(){const r=await client.from('market_profiles').select('wallet').eq('user_id',user.id).single();if(r.error)throw r.error;return r.data;}
async function browse(){note('讀取市場中…','#93c5fd');const q=document.getElementById('market-search-old')?.value||'';let req=client.from('market_listings').select('*').eq('status','active').order('created_at',{ascending:false}).limit(100);if(q)req=req.ilike('item_name','%'+q+'%');const r=await req;if(r.error)return note(esc(r.error.message),'#fca5a5');const rows=r.data||[];document.getElementById('market-body').innerHTML=`<div style="display:flex;gap:8px;margin-bottom:12px"><input id="market-search-old" value="${esc(q)}" placeholder="搜尋物品名稱" style="flex:1;background:#0f172a;border:1px solid #475569;border-radius:7px;padding:10px;color:white"><button onclick="marketSearch()">搜尋</button><button onclick="marketTab('browse')">重新整理</button></div>${rows.length?rows.map(l=>`<div style="display:grid;grid-template-columns:1fr auto;gap:12px;padding:12px;margin-bottom:8px;border:1px solid #334155;border-radius:9px;background:#172033"><div><b style="color:#fde68a">${esc(l.item_name)}</b><small style="display:block;color:#94a3b8;margin-top:4px">賣家 ${esc(l.seller_name)}｜數量 ${l.qty}｜單價 ${money(l.unit_price)}｜總價 ${money(l.qty*l.unit_price)}</small></div>${l.seller_id===user.id?'<span style="color:#94a3b8">自己的商品</span>':`<button onclick="marketBuy('${l.id}',${l.qty*l.unit_price})">購買</button>`}</div>`).join(''):'<div style="color:#94a3b8;padding:25px;text-align:center">目前沒有掛賣商品。</div>'}`;}
window.marketSearch=()=>browse();
function marketEquipment(it){const d=it&&DB.items[it.id];return !!(d&&['wpn','arm','acc'].includes(d.type)&&!d.isArrow&&!d.noSell&&(it.cnt||1)>0);}
function marketConsumable(it){const d=it&&DB.items[it.id];return !!(d&&!d.noSell&&(it.cnt||1)>0&&(d.type==='pot'||d.type==='misc'||d.type==='etc'||/^mat_/.test(it.id)));}
function marketEligible(it){return marketEquipment(it)||marketConsumable(it);}
function tradable(it){return marketEligible(it)&&!it.lock;}
function equippedCount(){return Object.values(player.eq||{}).flatMap(v=>Array.isArray(v)?v:[v]).filter(marketEquipment).length;}
window.marketUnlock=function(uidv){const it=(player.inv||[]).find(x=>String(x.uid)===String(uidv));if(!it)return;if(!confirm(`解除鎖定 ${itemTitle(it)}？`))return;it.lock=false;saveGame();renderTabs();sell();};
async function sell(){const all=(player.inv||[]).filter(marketEligible),arr=all.filter(it=>!it.lock),locked=all.filter(it=>it.lock),eqn=equippedCount();document.getElementById('market-body').innerHTML=`<div style="color:#fbbf24;margin-bottom:12px">裝備、製作材料與藥水皆可掛賣；上架後會立即離開背包，售出金額扣除 5% 手續費後進入交易錢包。</div><div style="margin-bottom:12px;padding:10px;border:1px solid #334155;border-radius:8px;color:#cbd5e1">背包可掛賣：<b style="color:#86efac">${arr.length}</b> 種｜鎖定：<b style="color:#fca5a5">${locked.length}</b> 種｜裝備中：<b style="color:#93c5fd">${eqn}</b> 件<br><small style="color:#94a3b8">堆疊材料與藥水可輸入販售數量；任務關鍵道具與標記為不可販售的物品不會顯示。</small></div>${arr.map(it=>`<div style="display:grid;grid-template-columns:1fr 75px 145px auto;gap:8px;align-items:center;padding:11px;margin-bottom:8px;border:1px solid #334155;border-radius:9px"><div><b>${esc(itemTitle(it))}</b><small style="display:block;color:#94a3b8">持有 ${it.cnt||1}｜${marketEquipment(it)?'裝備':DB.items[it.id].type==='pot'?'藥水':'材料'}</small></div><input id="mq-${it.uid}" type="number" min="1" max="${it.cnt||1}" value="1" title="數量" style="background:#0f172a;border:1px solid #475569;padding:9px;color:white;width:100%"><input id="mp-${it.uid}" type="number" min="1" value="10000" title="單價" style="background:#0f172a;border:1px solid #475569;padding:9px;color:white;width:100%"><button onclick="marketList('${it.uid}')">掛賣</button></div>`).join('')}${locked.map(it=>`<div style="display:flex;justify-content:space-between;align-items:center;gap:10px;padding:11px;margin-bottom:8px;border:1px solid #7f1d1d;border-radius:9px;background:#2b1720"><div><b>${esc(itemTitle(it))}</b><small style="display:block;color:#fca5a5">🔒 已鎖定，無法掛賣</small></div><button onclick="marketUnlock('${it.uid}')">解除鎖定</button></div>`).join('')}${all.length?'':'<div style="color:#94a3b8;padding:25px">背包內沒有可掛賣的裝備、材料或藥水。身上裝備請先卸下；任務關鍵道具無法交易。</div>'}`;}
window.marketList=async function(uidv){if(busy)return;const it=player.inv.find(x=>String(x.uid)===String(uidv)),d=it&&DB.items[it.id],qty=Math.floor(Number(document.getElementById('mq-'+uidv)?.value)),price=Math.floor(Number(document.getElementById('mp-'+uidv)?.value));if(!tradable(it)||qty<1||qty>(it.cnt||1)||price<1)return alert('數量或價格不正確。');if(!confirm(`掛賣 ${itemTitle(it)} ×${qty}，單價 ${money(price)} 金幣？`))return;busy=true;const data={...it};delete data.uid;delete data.cnt;delete data.lock;delete data.junk;try{const r=await client.rpc('market_create_listing',{p_item_id:it.id,p_item_name:itemTitle(it),p_item_data:data,p_qty:qty,p_unit_price:price});if(r.error)throw r.error;it.cnt-=qty;if(it.cnt<=0)player.inv=player.inv.filter(x=>x.uid!==it.uid);saveGame();renderTabs();await sell();}catch(e){alert('掛賣失敗：'+e.message);}finally{busy=false;}};
async function mine(){note('讀取我的掛賣…','#93c5fd');const r=await client.from('market_listings').select('*').eq('seller_id',user.id).order('created_at',{ascending:false}).limit(100);if(r.error)return note(esc(r.error.message),'#fca5a5');document.getElementById('market-body').innerHTML=(r.data||[]).map(l=>`<div style="display:flex;justify-content:space-between;gap:10px;padding:11px;margin-bottom:8px;border:1px solid #334155;border-radius:9px"><div><b>${esc(l.item_name)} ×${l.qty}</b><small style="display:block;color:#94a3b8">${l.status==='active'?'販售中':l.status==='sold'?'已售出':'已下架'}｜總價 ${money(l.qty*l.unit_price)}</small></div>${l.status==='active'?`<button onclick="marketCancel('${l.id}')">下架</button>`:''}</div>`).join('')||'<div style="color:#94a3b8;padding:25px">尚無掛賣紀錄。</div>';}
window.marketCancel=async id=>{if(busy||!confirm('確定下架？物品會送到「待領取」。'))return;busy=true;try{const r=await client.rpc('market_cancel',{p_listing:id});if(r.error)throw r.error;await mine();}catch(e){alert(e.message);}finally{busy=false;}};
window.marketBuy=async(id,total)=>{if(busy||!confirm(`確定使用交易錢包 ${money(total)} 金幣購買？`))return;busy=true;try{const r=await client.rpc('market_buy',{p_listing:id});if(r.error)throw r.error;alert('購買成功，請到「待領取」領取物品。');await browse();}catch(e){alert('購買失敗：'+e.message);}finally{busy=false;}};
async function deliveries(){const r=await client.from('market_deliveries').select('*').eq('owner_id',user.id).eq('claimed',false).order('created_at',{ascending:false});if(r.error)return note(esc(r.error.message),'#fca5a5');document.getElementById('market-body').innerHTML=(r.data||[]).map(d=>`<div style="display:flex;justify-content:space-between;gap:10px;padding:12px;margin-bottom:8px;border:1px solid #334155;border-radius:9px"><div><b>${esc(itemTitle(d.item_data))} ×${d.qty}</b><small style="display:block;color:#94a3b8">${d.source==='purchase'?'購買商品':'下架退回'}</small></div><button onclick="marketClaim('${d.id}')">領取</button></div>`).join('')||'<div style="color:#94a3b8;padding:25px">沒有待領取物品。</div>';}
window.marketClaim=async id=>{if(busy)return;busy=true;try{const r=await client.rpc('market_claim',{p_delivery:id});if(r.error)throw r.error;const raw=r.data.item,qty=Number(r.data.qty||1);if(!raw||!DB.items[raw.id])throw new Error('未知物品，請聯絡管理員');const inst={...raw,uid:uid(),cnt:qty,lock:false,junk:false};const ex=player.inv.find(x=>sameItemSig(x,inst)&&(x.en||0)===0&&!x.lock);if(ex)ex.cnt=(ex.cnt||1)+qty;else player.inv.push(inst);saveGame();renderTabs();await deliveries();}catch(e){alert('領取失敗：'+e.message);}finally{busy=false;}};
async function wallet(){try{const p=await profile();document.getElementById('market-body').innerHTML=`<div style="display:grid;gap:13px"><div style="padding:18px;border:1px solid #0ea5e9;border-radius:10px;background:#0c2540"><b style="font-size:22px;color:#7dd3fc">交易錢包：${money(p.wallet)} 金幣</b><div style="color:#94a3b8;margin-top:5px">遊戲角色金幣：${money(player.gold)}</div></div><div style="display:flex;gap:8px"><input id="market-wallet-amount" type="number" min="1" value="100000" style="flex:1;background:#0f172a;border:1px solid #475569;padding:11px;color:white"><button onclick="marketDeposit()">存入</button><button onclick="marketWithdraw()">提領</button></div><div style="color:#fbbf24">賣家實收售價的 95%。交易錢包由伺服器管理；存入或提領後會立即儲存本機角色。</div></div>`;}catch(e){note(esc(e.message),'#fca5a5');}}
window.marketDeposit=async()=>{if(busy)return;const a=Math.floor(Number(document.getElementById('market-wallet-amount').value));if(a<1||player.gold<a)return alert('遊戲金幣不足。');busy=true;player.gold-=a;try{const r=await client.rpc('market_deposit',{p_amount:a});if(r.error)throw r.error;saveGame();updateUI();await wallet();}catch(e){player.gold+=a;alert(e.message);}finally{busy=false;}};
window.marketWithdraw=async()=>{if(busy)return;const a=Math.floor(Number(document.getElementById('market-wallet-amount').value));if(a<1)return;busy=true;try{const r=await client.rpc('market_withdraw',{p_amount:a});if(r.error)throw r.error;player.gold+=a;saveGame();updateUI();await wallet();}catch(e){alert(e.message);}finally{busy=false;}};
})();
