/* Supabase 連線競技場：真人配對、伺服器回合計算、雙方同步戰報。 */
(function(){
'use strict';
let pc=null,pu=null,pTimer=null,pState={kind:'idle'},pBusy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ready=()=>window.MARKET_CONFIG&&window.supabase&&window.supabase.createClient;
function panel(){let p=document.getElementById('pvp-panel');if(p)return p;p=document.createElement('div');p.id='pvp-panel';p.innerHTML='<div class="pvp-window"><button class="pvp-x" onclick="pvpClose()">×</button><header><b>⚔ 連線競技場</b><small id="pvp-account"></small></header><div id="pvp-body"></div></div>';document.body.appendChild(p);let st=document.createElement('style');st.textContent=`#pvp-panel{display:none;position:fixed;inset:0;z-index:14000;background:#020617e8;align-items:center;justify-content:center;padding:12px}.pvp-window{position:relative;width:min(920px,98vw);max-height:94vh;overflow:auto;color:#f8fafc;background:radial-gradient(circle at 50% 0,#451a03,#111827 48%);border:2px solid #f59e0b;border-radius:16px;padding:20px;box-shadow:0 0 45px #dc262666}.pvp-window header b{font-size:26px;color:#fde68a}.pvp-window header small{display:block;color:#94a3b8;margin-top:3px}.pvp-x{position:absolute;right:12px;top:8px;font-size:30px;color:#fff}.pvp-card{background:#0f172ae6;border:1px solid #92400e;border-radius:11px;padding:14px;margin:10px 0}.pvp-actions{display:flex;gap:10px;justify-content:center;flex-wrap:wrap;margin:15px 0}.pvp-actions button,.pvp-window button.pvp-btn{padding:10px 20px;border:1px solid #f59e0b;border-radius:9px;background:#9a3412;color:#fff7ed;font-weight:bold}.pvp-duel{display:grid;grid-template-columns:1fr 90px 1fr;gap:14px;align-items:center}.pvp-fighter{background:#111827;border:1px solid #475569;border-radius:12px;padding:14px}.pvp-fighter.mine{border-color:#38bdf8;box-shadow:0 0 14px #0ea5e944}.pvp-fighter h3{font-size:21px;color:#fde68a}.pvp-hp{height:20px;background:#334155;border-radius:10px;overflow:hidden;margin:8px 0}.pvp-hp>i{display:block;height:100%;background:linear-gradient(90deg,#991b1b,#ef4444);transition:width .35s}.pvp-vs{text-align:center;font-size:30px;font-weight:bold;color:#fb923c}.pvp-log{max-height:280px;overflow:auto;background:#020617;border:1px solid #334155;border-radius:10px;padding:9px}.pvp-log div{padding:6px 8px;border-bottom:1px solid #1e293b}.pvp-result{text-align:center;font-size:25px;font-weight:bold;padding:16px;color:#facc15}@media(max-width:650px){.pvp-duel{grid-template-columns:1fr}.pvp-vs{font-size:20px}.pvp-window{padding:14px}}`;document.head.appendChild(st);return p;}
function body(){return document.getElementById('pvp-body');}
function note(t,c='#fbbf24'){body().innerHTML=`<div class="pvp-card" style="text-align:center;color:${c}">${t}</div>`;}
async function init(){if(!ready())throw new Error('Supabase 尚未設定。');if(!pc)pc=window.supabase.createClient(MARKET_CONFIG.url,MARKET_CONFIG.anonKey,{auth:{persistSession:true,autoRefreshToken:true}});let {data:{session}}=await pc.auth.getSession();if(!session){let r=await pc.auth.signInAnonymously();if(r.error)throw r.error;session=r.data.session;}pu=session.user;let n=(window.player&&player.name)||'冒險者';let e=await pc.rpc('market_ensure_profile',{p_name:n});if(e.error)throw e.error;let id=await pc.rpc('player_my_identity');let tag=!id.error&&id.data&&id.data.player_tag;document.getElementById('pvp-account').textContent=`${n}｜${tag?'@'+tag:'請先設定玩家 ID'}`;}
function pvpForm(){let morph='',avatar=player.avatar||'',weapon='sword1';try{if(typeof _playerMorphName==='function')morph=_playerMorphName()||'';if(typeof CLASS_ANIM_SETS!=='undefined'&&CLASS_ANIM_SETS[avatar]&&typeof _classAnimWpnKey==='function')weapon=_classAnimWpnKey(player,CLASS_ANIM_SETS[avatar])||weapon;}catch(e){}return{morph,avatar,weapon};}
function pvpBuffs(){let out=[],b=player.buffs||{};Object.keys(b).forEach(id=>{let t=Math.ceil(Number(b[id])||0);if(t<=0||id==='poly')return;let sk=(typeof DB!=='undefined'&&DB.skills&&DB.skills[id])||null,n=(sk&&sk.n)||((typeof BUFF_NAMES!=='undefined'&&BUFF_NAMES[id])||id);out.push({id:String(id).slice(0,40),n:String(n).slice(0,30),t:Math.min(86400,t)});});return out.slice(0,24);}
function pvpStatuses(){let names={stun:'暈眩',freeze:'冰凍',stone:'石化',poison:'中毒',burn:'燃燒',scald:'灼傷',bleed:'出血',sleep:'睡眠',silence:'沉默',paralyze:'麻痺',magicseal:'魔法封印',armorBreak:'破甲',slowAtk:'攻速降低',cleave:'撕裂'},out=[],s=player.statuses||{};Object.keys(names).forEach(id=>{let ticks=Number(s[id])||0;if(ticks>0)out.push({id,n:names[id],t:Math.ceil(ticks/10),dmg:Math.max(0,Math.round(Number(s[id+'Dmg'])||0))});});return out;}
function pvpDiceAverage(v){if(!Array.isArray(v)||v.length<2)return 0;return Math.max(0,Number(v[0])||0)*(Math.max(1,Number(v[1])||1)+1)/2;}
function pvpSelectedSkill(){let id=document.getElementById('sel-atk-skill')?.value||'',sk=(window.DB&&DB.skills&&DB.skills[id])||null;if(!sk||sk.type!=='atk')return null;let power=pvpDiceAverage(sk.dmgDice);if(Array.isArray(sk.multiDmg))power=sk.multiDmg.reduce((n,x)=>n+pvpDiceAverage(x),0);let status=sk.status||null;if(!status&&sk.stun)status={kind:'stun',dur:Math.max(1,Math.round(Number(sk.stun)/100)),pbase:Math.round((Number(sk.stunChance)||.1)*100)};if(!status&&sk.freeze)status={kind:'freeze',dur:Math.max(1,Math.round(Number(sk.freeze)/100)),pbase:20};return{id,n:sk.n||id,type:sk.dmgType==='magic'?'magic':(sk.ranged?'ranged':'physical'),mp:Math.max(0,Number(sk.mp)||0),hp:Math.max(0,Number(sk.hpCost)||0),power:Math.max(0,Math.round(power+Number(sk.skillAddDmg||0))),hits:Math.max(1,Math.min(8,Number(sk.hits)||1)),lifesteal:!!sk.lifesteal,status:status?{kind:String(status.kind||'').slice(0,20),chance:Math.max(5,Math.min(80,Math.round(Number(status.pbase||20)))),dur:Math.max(1,Math.min(30,Math.round(Number(status.dur)||2)))}:null};}
function pvpSelectedHeal(){let id=document.getElementById('sel-heal-skill')?.value||'',sk=(window.DB&&DB.skills&&DB.skills[id])||null;if(!sk||sk.type!=='heal')return null;let heal=Number(sk.healBase||0)+pvpDiceAverage(sk.healDice||sk.valDice);return{id,n:sk.n||id,mp:Math.max(0,Number(sk.mp)||0),heal:Math.max(1,Math.round(heal)),hot:!!sk.hot};}
function pvpPassives(){let allow=['sk_resurrection','sk_warrior_berserk','sk_warrior_titan_rock','sk_warrior_titan_bullet','sk_warrior_titan_magic','sk_royal_kingguard','sk_dragon_deadlybody','sk_dark_double','sk_dark_burn','sk_counter_barrier','sk_holy_barrier','sk_elf_mirror','sk_elf_preciseshot','sk_elf_attrfire','sk_abs_barrier'];let learned=new Set(player.skills||[]),buff=new Set(Object.keys(player.buffs||{}).filter(k=>Number(player.buffs[k])>0));return allow.filter(x=>learned.has(x)||buff.has(x));}
function snapshot(){if(typeof recomputeStats==='function')recomputeStats();else if(typeof calcStats==='function')calcStats();let d=player.d||{},f=pvpForm(),we=(player.eq&&player.eq.wpn)||null,w=(we&&window.DB&&DB.items)?DB.items[we.id]:null,skill=pvpSelectedSkill(),ranged=!!(w&&(w.isBow||w.ranged||w.type==='bow'))||f.weapon==='bow',type=skill?.type==='magic'?'magic':(ranged?'ranged':'melee'),atk=type==='magic'?Number(d.magicDmg||0)+Number(d.extraMp||0):(type==='ranged'?Number(d.rangedDmg||0):Number(d.meleeDmg||0))+Number(d.extraDmg||0),hit=type==='magic'?Number(d.magicHit||0):(type==='ranged'?Number(d.rangedHit||0):Number(d.meleeHit||0))+Number(d.extraHit||0),crit=type==='magic'?Number(d.magicCrit||0):(type==='ranged'?Number(d.rangedCrit||0):Number(d.meleeCrit||0)),critDmg=type==='magic'?Number(d.magicCritDmg||50):(type==='ranged'?Number(d.rangedCritDmg||50):Number(d.meleeCritDmg||50)),weaponRoll=w?((Number(w.dmgS||1)+1)/2+Math.max(0,Number(we.en||0))):1;return{version:2,lv:Math.round(Number(player.lv||1)),class:player.cls||'冒險者',avatar:f.avatar,morph:f.morph,weapon:f.weapon,attack_type:type,buffs:pvpBuffs(),statuses:pvpStatuses(),passives:pvpPassives(),skill,heal:pvpSelectedHeal(),max_hp:Math.round(Math.max(100,Number(player.mhp||player.hp||100))),max_mp:Math.round(Math.max(0,Number(player.mmp||player.mp||0))),atk:Math.round(Math.max(1,atk)),weapon_roll:Math.round(Math.max(1,weaponRoll)),hit:Math.round(hit),crit:Math.round(crit*10)/10,crit_dmg:Math.round(Math.max(25,critDmg)),interval:Math.round(Math.max(.1,Number(d.aspd||1))*100)/100,ac:Math.round(Number(d.ac||10)),mr:Math.round(Number(d.mr||0)),dr:Math.round(Number(d.dr||0)),er:Math.round(Number(d.er||0)),hp_regen:Math.round(Number(d.hpR||0)),mp_regen:Math.round(Number(d.mpR||0)),mp_reduce:Math.round(Number(d.mpReduce||0)),res_fire:Math.round(Number(d.resFire||0)),res_water:Math.round(Number(d.resWater||0)),res_wind:Math.round(Number(d.resWind||0)),res_earth:Math.round(Number(d.resEarth||0)),imm_poison:!!d.immPoison,imm_stone:!!d.immStone};}
function recordHtml(r={}){return `<div class="pvp-card" style="display:flex;justify-content:space-around;gap:8px;flex-wrap:wrap"><b>競技積分 ${Number(r.rating||1000)}</b><span>勝 ${Number(r.wins||0)}</span><span>敗 ${Number(r.losses||0)}</span><span>和 ${Number(r.draws||0)}</span></div>`;}
function renderIdle(s){body().innerHTML=`<div class="pvp-card"><h2 style="font-size:22px;color:#fdba74">真人連線自動 PK</h2><p>完整同步角色的攻擊類型、命中、AC／MR／減傷、閃避、攻速、HP／MP恢復、增益、異常、職業被動與自動攻擊／治癒技能。</p><small style="color:#94a3b8">進場倒數 5 秒後開戰；伺服器依實際攻擊間隔決定出手，不再把角色數值換算成假攻防。勝利 +15 分，失敗 -10 分，平手 +2 分。</small></div>${recordHtml(s)}<div class="pvp-actions"><button onclick="pvpStart()">開始配對</button></div>`;}
function renderQueue(s){body().innerHTML=`${recordHtml(s)}<div class="pvp-card" style="text-align:center"><div style="font-size:46px">⚔</div><h2 style="font-size:22px;color:#fde68a">尋找對手中…</h2><p>${esc(s.message||'等待另一位玩家')}</p><small style="color:#94a3b8">請保持此視窗開啟，配對成功會自動進入戰鬥。</small></div><div class="pvp-actions"><button onclick="pvpCancel()">取消配對</button></div>`;}
function stateBadges(st){let used=Number((window.PVP_VISUAL_STATE||{}).elapsed_seconds)||0,rows=[...(st.buffs||[]).map(x=>({...x,t:Math.max(0,(Number(x.t)||0)-used),bad:false})),...(st.statuses||[]).map(x=>({...x,t:Number(x.t)||0,bad:true}))].filter(x=>x.t>0);return rows.length?`<div class="pvp-state-list">${rows.map(x=>`<span class="${x.bad?'bad':'good'}" title="${esc(x.n)}｜剩餘 ${Number(x.t)||0} 秒"><img src="assets/state-icons/${encodeURIComponent(x.n)}.jpg" onerror="this.style.display='none'">${esc(x.n)} <b>${Number(x.t)||0}s</b></span>`).join('')}</div>`:'<div class="pvp-state-list empty">無增益／異常狀態</div>';}
function fighter(x,side,mine){let st=x.stats||{},hp=Number(x.hp||0),max=Number(st.max_hp||1),mp=Number(x.mp??st.max_mp??0),mmp=Number(st.max_mp||0),pct=Math.max(0,Math.min(100,hp/max*100)),kind={melee:'近戰',ranged:'遠攻',magic:'魔法'}[st.attack_type]||'近戰';return `<div class="pvp-fighter ${mine===side?'mine':''}"><h3>${mine===side?'⭐ ':''}${esc(x.name)}</h3><small>${x.tag?'@'+esc(x.tag)+'｜':''}Lv.${st.lv||1} ${esc(st.class||'')}${st.morph?'｜變身：'+esc(st.morph):''}</small><div class="pvp-hp"><i style="width:${pct}%"></i></div><b>HP ${hp.toLocaleString()} / ${max.toLocaleString()}</b>${mmp?`<small style="display:block;color:#60a5fa">MP ${mp.toLocaleString()} / ${mmp.toLocaleString()}</small>`:''}<small style="display:block;color:#94a3b8;margin-top:6px">${kind}傷害 ${st.atk}｜命中 ${st.hit}｜爆擊 ${st.crit}%<br>AC ${st.ac}｜MR ${st.mr}｜減傷 ${st.dr}｜閃避 ${st.er}%<br>攻擊間隔 ${st.interval} 秒${st.skill?`｜技能 ${esc(st.skill.n)}`:''}</small>${stateBadges(st)}</div>`;}
function renderMatch(s){window.PVP_VISUAL_STATE=s;let logs=(s.log||[]).slice(-18).reverse().map(x=>{let a=x.skill1?`【${esc(x.skill1)}】`:'' ,b=x.skill2?`【${esc(x.skill2)}】`:'' ,extra=[];if(x.heal1)extra.push(`${esc(s.player1.name)} 回復 ${Number(x.heal1).toLocaleString()} HP`);if(x.heal2)extra.push(`${esc(s.player2.name)} 回復 ${Number(x.heal2).toLocaleString()} HP`);if(x.reflect1)extra.push(`${esc(s.player1.name)} 反擊 ${Number(x.reflect1).toLocaleString()}`);if(x.reflect2)extra.push(`${esc(s.player2.name)} 反擊 ${Number(x.reflect2).toLocaleString()}`);return `<div><b style="color:#fde68a">第 ${x.round} 回合</b>　${a}${esc(s.player1.name)} 造成 <span style="color:#fb923c">${Number(x.d1).toLocaleString()}</span>${x.c1?'（爆擊）':''}，${b}${esc(s.player2.name)} 造成 <span style="color:#60a5fa">${Number(x.d2).toLocaleString()}</span>${x.c2?'（爆擊）':''}${extra.length?'｜'+extra.join('、'):''}${x.note?'｜'+esc(x.note):''}</div>`}).join('');let done=s.status==='finished',won=s.winner_id&&s.winner_id===pu.id,draw=done&&!s.winner_id,count=Math.max(0,Math.ceil(Number(s.countdown)||0)),phase=count>0?`<div class="pvp-card pvp-waiting" style="text-align:center;color:#fde68a">配對成功！<b>${count}</b> 秒後開始戰鬥</div>`:'<div class="pvp-card" style="text-align:center;color:#93c5fd">雙方正在依真實攻速、技能與狀態自動交戰…</div>';body().innerHTML=`<div class="pvp-duel">${fighter(s.player1,1,s.my_side)}<div class="pvp-vs">VS<br><small>回合 ${s.round}</small></div>${fighter(s.player2,2,s.my_side)}</div>${done?`<div class="pvp-result" style="color:${draw?'#cbd5e1':won?'#86efac':'#fca5a5'}">${draw?'平手':won?'🏆 勝利':'戰敗'}<br><small>${esc(s.result_text||'戰鬥結束')}</small></div>`:phase}<div class="pvp-log">${logs||'<div>戰鬥即將開始…</div>'}</div>${done?recordHtml(s.record):''}<div class="pvp-actions">${done?'<button onclick="pvpStart()">再次配對</button>':'<button onclick="pvpForfeit()">投降</button>'}</div>`;}
function render(s){pState=s||{kind:'idle'};if(pState.kind==='queued')renderQueue(pState);else if(pState.kind==='match')renderMatch(pState);else renderIdle(pState);}
function schedule(){clearTimeout(pTimer);if(document.getElementById('pvp-panel')?.style.display!=='flex')return;if(pState.kind==='queued'||(pState.kind==='match'&&pState.status==='active'))pTimer=setTimeout(step,400);}
async function step(){if(pBusy)return schedule();pBusy=true;try{let r=pState.kind==='match'?await pc.rpc('pvp_tick',{p_match:pState.id}):await pc.rpc('pvp_poll');if(r.error)throw r.error;render(r.data);}catch(e){note(esc(e.message),'#fca5a5');}finally{pBusy=false;schedule();}}
window.pvpOpen=async()=>{let p=panel();p.style.display='flex';note('正在連線競技場…','#93c5fd');try{await init();let r=await pc.rpc('pvp_poll');if(r.error)throw r.error;render(r.data);schedule();}catch(e){note(`${esc(e.message)}<br><br>請先到 Supabase SQL Editor 執行 <b>supabase-pvp.sql</b>。`,'#fca5a5');}};
window.pvpClose=async()=>{clearTimeout(pTimer);if(pState.kind==='queued'&&pc)await pc.rpc('pvp_cancel_queue');let p=document.getElementById('pvp-panel');if(p)p.style.display='none';};
window.pvpStart=async()=>{if(pBusy)return;pBusy=true;note('正在加入配對…','#93c5fd');try{let r=await pc.rpc('pvp_join_queue',{p_snapshot:snapshot()});if(r.error)throw r.error;render(r.data);}catch(e){note(esc(e.message),'#fca5a5');}finally{pBusy=false;schedule();}};
window.pvpCancel=async()=>{clearTimeout(pTimer);let r=await pc.rpc('pvp_cancel_queue');if(r.error)return alert(r.error.message);pState={kind:'idle'};let s=await pc.rpc('pvp_poll');render(s.data);};
window.pvpForfeit=async()=>{if(!confirm('確定要投降並判定本場失敗嗎？'))return;let r=await pc.rpc('pvp_forfeit',{p_match:pState.id});if(r.error)return alert(r.error.message);render(r.data);};
})();

/* PvP visual battle layer: turns the synchronized combat result into an animated scene. */
(function(){
'use strict';
let lastKey='', observer=null;
const classAvatar={royal:'王子',knight:'男騎士',elf:'男妖精',mage:'男法師',darkelf:'男黑暗妖精',dragonknight:'男龍騎士',illusion:'男幻術士',warrior:'男戰士','王族':'王子','騎士':'男騎士','妖精':'男妖精','法師':'男法師','黑暗妖精':'男黑暗妖精','龍騎士':'男龍騎士','幻術士':'男幻術士','戰士':'男戰士'};
const clsWeapon={elf:'bow',mage:'wand',darkelf:'dagger',illusion:'wand',warrior:'sword2'};
function css(){if(document.getElementById('pvp-visual-css'))return;let s=document.createElement('style');s.id='pvp-visual-css';s.textContent=`
.pvp-arena{height:330px;position:relative;overflow:hidden;margin:12px 0 15px;border:2px solid #b45309;border-radius:15px;background:linear-gradient(#02061744,#02061799),url('assets/area/冥法軍訓練場.jpg') center/cover;box-shadow:inset 0 -55px 60px #020617cc,0 0 24px #f59e0b33}
.pvp-arena:after{content:'';position:absolute;left:5%;right:5%;bottom:28px;height:34px;border-radius:50%;background:#02061766;filter:blur(13px)}
.pvp-round{position:absolute;z-index:8;left:50%;top:12px;transform:translateX(-50%);padding:6px 17px;border:1px solid #f59e0b;border-radius:20px;background:#020617d9;color:#fde68a;font-weight:900;box-shadow:0 0 18px #f59e0b77}
.pvp-actor{position:absolute;z-index:4;bottom:32px;width:40%;height:235px;display:flex;align-items:flex-end;justify-content:center;transition:filter .2s,opacity .3s}.pvp-actor.a{left:2%}.pvp-actor.b{right:2%}
.pvp-sprite-wrap{position:relative;height:190px;width:190px;display:flex;align-items:flex-end;justify-content:center;filter:drop-shadow(0 9px 6px #000b)}
.pvp-sprite{max-width:180px;max-height:190px;image-rendering:auto;object-fit:contain;transform-origin:50% 85%}.pvp-actor.b .pvp-sprite{transform:scaleX(-1)}
.pvp-name{position:absolute;z-index:7;top:48px;width:38%;text-align:center;color:#fff;font-size:17px;font-weight:900;text-shadow:0 2px 4px #000}.pvp-name.a{left:3%}.pvp-name.b{right:3%}.pvp-name small{display:block;color:#cbd5e1;font-size:12px}
.pvp-stage-hp{height:12px;margin:5px auto 0;max-width:220px;background:#111827;border:1px solid #f8fafc99;border-radius:8px;overflow:hidden}.pvp-stage-hp i{display:block;height:100%;background:linear-gradient(90deg,#b91c1c,#ef4444,#fb7185);transition:width .3s}
.pvp-damage{position:absolute;z-index:12;left:50%;top:46px;transform:translateX(-50%);font-size:34px;font-weight:1000;color:#facc15;-webkit-text-stroke:1px #7f1d1d;text-shadow:0 4px 8px #000;opacity:0;pointer-events:none}.pvp-damage.crit{font-size:44px;color:#ff3535;text-shadow:0 0 14px #ef4444,0 4px 8px #000}
.pvp-actor.attack-a{animation:pvpLungeA .42s ease}.pvp-actor.attack-b{animation:pvpLungeB .42s ease}.pvp-actor.hurt{animation:pvpHurt .34s ease;filter:brightness(2) sepia(1) hue-rotate(300deg) drop-shadow(0 0 14px #ef4444)}.pvp-damage.show{animation:pvpFloat .75s ease-out}.pvp-actor.dead{animation:pvpFall .8s forwards;filter:grayscale(1) brightness(.55)}
.pvp-impact{position:absolute;z-index:6;left:50%;bottom:105px;width:90px;height:90px;border-radius:50%;opacity:0;background:radial-gradient(circle,#fff 0,#facc15 14%,#ef4444aa 32%,transparent 67%)}.pvp-impact.show{animation:pvpImpact .35s ease-out}
.pvp-state-list{display:flex;gap:5px;flex-wrap:wrap;margin-top:9px}.pvp-state-list span{display:flex;align-items:center;gap:4px;padding:3px 7px;border-radius:12px;font-size:11px}.pvp-state-list span.good{background:#064e3b;color:#a7f3d0}.pvp-state-list span.bad{background:#7f1d1d;color:#fecaca}.pvp-state-list img{width:18px;height:18px;object-fit:cover;border-radius:3px}.pvp-state-list.empty{font-size:11px;color:#64748b}.pvp-stage-effects{display:flex;justify-content:center;gap:3px;margin-top:4px;height:20px}.pvp-stage-effects span{width:19px;height:19px;display:grid;place-items:center;border-radius:50%;font-size:11px;background:#065f46;border:1px solid #6ee7b7}.pvp-stage-effects span.bad{background:#991b1b;border-color:#fca5a5}.pvp-countdown{position:absolute;z-index:30;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;background:#0206178f;color:#fff;text-shadow:0 4px 15px #000;font-weight:1000}.pvp-countdown b{font-size:92px;line-height:1;color:#fde047;-webkit-text-stroke:2px #9a3412;animation:pvpCountPulse .8s ease infinite}.pvp-countdown small{font-size:20px;margin-top:8px;color:#fef3c7}.pvp-waiting b{font-size:24px;color:#facc15}.pvp-actor.hard-control{filter:hue-rotate(165deg) saturate(.6) drop-shadow(0 0 13px #67e8f9)}.pvp-actor.poisoned{filter:drop-shadow(0 0 13px #4ade80)}
@keyframes pvpLungeA{0%,100%{transform:translateX(0)}45%{transform:translateX(115px) scale(1.09)}}@keyframes pvpLungeB{0%,100%{transform:translateX(0)}45%{transform:translateX(-115px) scale(1.09)}}@keyframes pvpHurt{0%,100%{transform:translateX(0)}25%{transform:translateX(-13px)}50%{transform:translateX(13px)}75%{transform:translateX(-8px)}}@keyframes pvpFloat{0%{opacity:0;transform:translate(-50%,18px) scale(.6)}20%{opacity:1;transform:translate(-50%,0) scale(1.18)}100%{opacity:0;transform:translate(-50%,-70px) scale(.95)}}@keyframes pvpImpact{0%{opacity:1;transform:scale(.25)}100%{opacity:0;transform:scale(1.8)}}@keyframes pvpFall{100%{transform:rotate(78deg) translate(35px,28px);opacity:.6}}
@keyframes pvpCountPulse{0%{transform:scale(.75);opacity:.2}45%{transform:scale(1.16);opacity:1}100%{transform:scale(1);opacity:.9}}
@media(max-width:650px){.pvp-arena{height:265px}.pvp-sprite-wrap{width:125px;height:145px}.pvp-sprite{max-width:125px;max-height:145px}.pvp-name{top:42px;font-size:14px}.pvp-actor{height:175px}.pvp-actor.attack-a{animation-name:pvpLungeAm}.pvp-actor.attack-b{animation-name:pvpLungeBm}@keyframes pvpLungeAm{45%{transform:translateX(48px) scale(1.08)}}@keyframes pvpLungeBm{45%{transform:translateX(-48px) scale(1.08)}}}
`;document.head.appendChild(s)}
function text(el){return (el&&el.textContent||'').trim()}
function parseFighter(el,mine){let title=text(el.querySelector('h3')).replace(/^你\s*/,'')||'冒險者',sub=text(el.querySelector('small')),hpText=text(el.querySelector('b')),nums=hpText.match(/[\d,]+/g)||['0','1'],hp=Number(nums[0].replace(/,/g,''))||0,max=Number((nums[1]||'1').replace(/,/g,''))||1,cls=(sub.match(/Lv\.\d+\s+(.+)$/)||[])[1]||'knight',key=String(cls).trim(),avatar=mine&&window.player&&player.avatar?player.avatar:(classAvatar[key]||classAvatar[key.toLowerCase()]||'男騎士'),weapon=clsWeapon[key.toLowerCase()]||'sword1';return{title,sub,hp,max,avatar,weapon}}
function path(f,act,n=0){return f.morph?`assets/morphanim/${encodeURIComponent(f.morph)}/${act}_${n}.png`:`assets/classanim/${encodeURIComponent(f.avatar)}/${f.weapon}_${act}_${n}.png`}
function stageEffects(f){let rows=[...(f.buffs||[]).slice(0,6).map(x=>({...x,bad:false})),...(f.statuses||[]).slice(0,6).map(x=>({...x,bad:true}))];return `<div class="pvp-stage-effects">${rows.map(x=>`<span class="${x.bad?'bad':''}" title="${x.n} ${x.t}s">${x.bad?'!':'✦'}</span>`).join('')}</div>`}
function actor(f,side){let pct=Math.max(0,Math.min(100,f.hp/f.max*100)),ids=(f.statuses||[]).map(x=>x.id),hard=ids.some(x=>['stun','freeze','stone','sleep','paralyze'].includes(x)),poison=ids.some(x=>['poison','burn','bleed','scald'].includes(x));return `<div class="pvp-name ${side}">${f.title}<small>${f.morph?'變身：'+f.morph:f.sub}</small><div class="pvp-stage-hp"><i style="width:${pct}%"></i></div>${stageEffects(f)}</div><div class="pvp-actor ${side}${f.hp<=0?' dead':''}${hard?' hard-control':''}${poison?' poisoned':''}" data-avatar="${f.avatar}" data-weapon="${f.weapon}" data-morph="${f.morph||''}"><div class="pvp-sprite-wrap"><img class="pvp-sprite" src="${path(f,'idle')}" onerror="this.onerror=null;this.src='assets/classanim/%E7%94%B7%E9%A8%8E%E5%A3%AB/sword1_idle_0.png'"><b class="pvp-damage"></b></div></div>`}
function build(body){let duel=body.querySelector('.pvp-duel');if(!duel||body.querySelector('.pvp-arena'))return;let cards=duel.querySelectorAll('.pvp-fighter');if(cards.length<2)return;let a=parseFighter(cards[0],cards[0].classList.contains('mine')),b=parseFighter(cards[1],cards[1].classList.contains('mine')),s=window.PVP_VISUAL_STATE||{},sa=(s.player1&&s.player1.stats)||{},sb=(s.player2&&s.player2.stats)||{},used=Number(s.elapsed_seconds)||0,buffs=x=>(x||[]).map(v=>({...v,t:Math.max(0,(Number(v.t)||0)-used)})).filter(v=>v.t>0),statuses=x=>(x||[]).filter(v=>(Number(v.t)||0)>0);Object.assign(a,{avatar:sa.avatar||a.avatar,weapon:sa.weapon||a.weapon,morph:sa.morph||'',buffs:buffs(sa.buffs),statuses:statuses(sa.statuses)});Object.assign(b,{avatar:sb.avatar||b.avatar,weapon:sb.weapon||b.weapon,morph:sb.morph||'',buffs:buffs(sb.buffs),statuses:statuses(sb.statuses)});let round=(text(duel.querySelector('.pvp-vs')).match(/\d+/)||['0'])[0],count=Math.max(0,Math.ceil(Number(s.countdown)||0)),stage=document.createElement('div');stage.className='pvp-arena';stage.innerHTML=`<div class="pvp-round">第 ${round} 回合</div>${actor(a,'a')}${actor(b,'b')}<i class="pvp-impact"></i>${count>0?`<div class="pvp-countdown"><b>${count}</b><small>準備戰鬥</small></div>`:''}`;duel.before(stage);if(count>0)return;let row=body.querySelector('.pvp-log div'),spans=row?row.querySelectorAll('span'):[],key=`${text(row)}|${a.hp}|${b.hp}`;if(row&&key!==lastKey){lastKey=key;let d1=spans[0]?Number(text(spans[0]).replace(/,/g,'')):0,d2=spans[1]?Number(text(spans[1]).replace(/,/g,'')):0,crit=/爆擊/.test(text(row));setTimeout(()=>strike(stage,'a','b',d1,crit),35);setTimeout(()=>strike(stage,'b','a',d2,crit),105)}}
function frames(actor,act,count,done){let img=actor.querySelector('.pvp-sprite'),av=actor.dataset.avatar,w=actor.dataset.weapon,m=actor.dataset.morph,i=0,src=n=>m?`assets/morphanim/${encodeURIComponent(m)}/${act}_${n}.png`:`assets/classanim/${encodeURIComponent(av)}/${w}_${act}_${n}.png`,idle=()=>m?`assets/morphanim/${encodeURIComponent(m)}/idle_0.png`:`assets/classanim/${encodeURIComponent(av)}/${w}_idle_0.png`,t=setInterval(()=>{img.src=src(i++);if(i>=count){clearInterval(t);setTimeout(()=>{img.src=idle();done&&done()},35)}},55)}
function strike(stage,from,to,damage,crit){if(!damage)return;let a=stage.querySelector(`.pvp-actor.${from}`),b=stage.querySelector(`.pvp-actor.${to}`),n=b.querySelector('.pvp-damage'),impact=stage.querySelector('.pvp-impact');if(!a||!b)return;a.classList.add(`attack-${from}`);frames(a,'attack',6);setTimeout(()=>{b.classList.add('hurt');frames(b,'hurt',2);n.textContent=`-${damage.toLocaleString()}${crit?' 爆擊！':''}`;n.className=`pvp-damage show${crit?' crit':''}`;impact.classList.add('show');setTimeout(()=>{a.classList.remove(`attack-${from}`);b.classList.remove('hurt');impact.classList.remove('show')},430)},185)}
function watch(){css();let b=document.getElementById('pvp-body');if(!b||b.dataset.visualWatch)return;b.dataset.visualWatch='1';observer=new MutationObserver(()=>build(b));observer.observe(b,{childList:true,subtree:true});build(b)}
new MutationObserver(()=>watch()).observe(document.documentElement,{childList:true,subtree:true});if(document.readyState!=='loading')watch();else document.addEventListener('DOMContentLoaded',watch);
})();
