/* Supabase 連線競技場：真人配對、伺服器回合計算、雙方同步戰報。 */
(function(){
'use strict';
let pc=null,pu=null,pTimer=null,pState={kind:'idle'},pBusy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ready=()=>window.MARKET_CONFIG&&window.supabase&&window.supabase.createClient;
function panel(){let p=document.getElementById('pvp-panel');if(p)return p;p=document.createElement('div');p.id='pvp-panel';p.innerHTML='<div class="pvp-window"><button class="pvp-x" onclick="pvpClose()">×</button><header><b>⚔ 連線競技場</b><small id="pvp-account"></small></header><div id="pvp-body"></div></div>';document.body.appendChild(p);let st=document.createElement('style');st.textContent=`#pvp-panel{display:none;position:fixed;inset:0;z-index:14000;background:#020617e8;align-items:center;justify-content:center;padding:12px}.pvp-window{position:relative;width:min(920px,98vw);max-height:94vh;overflow:auto;color:#f8fafc;background:radial-gradient(circle at 50% 0,#451a03,#111827 48%);border:2px solid #f59e0b;border-radius:16px;padding:20px;box-shadow:0 0 45px #dc262666}.pvp-window header b{font-size:26px;color:#fde68a}.pvp-window header small{display:block;color:#94a3b8;margin-top:3px}.pvp-x{position:absolute;right:12px;top:8px;font-size:30px;color:#fff}.pvp-card{background:#0f172ae6;border:1px solid #92400e;border-radius:11px;padding:14px;margin:10px 0}.pvp-actions{display:flex;gap:10px;justify-content:center;flex-wrap:wrap;margin:15px 0}.pvp-actions button,.pvp-window button.pvp-btn{padding:10px 20px;border:1px solid #f59e0b;border-radius:9px;background:#9a3412;color:#fff7ed;font-weight:bold}.pvp-duel{display:grid;grid-template-columns:1fr 90px 1fr;gap:14px;align-items:center}.pvp-fighter{background:#111827;border:1px solid #475569;border-radius:12px;padding:14px}.pvp-fighter.mine{border-color:#38bdf8;box-shadow:0 0 14px #0ea5e944}.pvp-fighter h3{font-size:21px;color:#fde68a}.pvp-hp{height:20px;background:#334155;border-radius:10px;overflow:hidden;margin:8px 0}.pvp-hp>i{display:block;height:100%;background:linear-gradient(90deg,#991b1b,#ef4444);transition:width .35s}.pvp-vs{text-align:center;font-size:30px;font-weight:bold;color:#fb923c}.pvp-log{max-height:280px;overflow:auto;background:#020617;border:1px solid #334155;border-radius:10px;padding:9px}.pvp-log div{padding:6px 8px;border-bottom:1px solid #1e293b}.pvp-result{text-align:center;font-size:25px;font-weight:bold;padding:16px;color:#facc15}@media(max-width:650px){.pvp-duel{grid-template-columns:1fr}.pvp-vs{font-size:20px}.pvp-window{padding:14px}}`;document.head.appendChild(st);return p;}
function body(){return document.getElementById('pvp-body');}
function note(t,c='#fbbf24'){body().innerHTML=`<div class="pvp-card" style="text-align:center;color:${c}">${t}</div>`;}
async function init(){if(!ready())throw new Error('Supabase 尚未設定。');if(!pc)pc=window.supabase.createClient(MARKET_CONFIG.url,MARKET_CONFIG.anonKey,{auth:{persistSession:true,autoRefreshToken:true}});let {data:{session}}=await pc.auth.getSession();if(!session){let r=await pc.auth.signInAnonymously();if(r.error)throw r.error;session=r.data.session;}pu=session.user;let n=(window.player&&player.name)||'冒險者';let e=await pc.rpc('market_ensure_profile',{p_name:n});if(e.error)throw e.error;let id=await pc.rpc('player_my_identity');let tag=!id.error&&id.data&&id.data.player_tag;document.getElementById('pvp-account').textContent=`${n}｜${tag?'@'+tag:'請先設定玩家 ID'}`;}
function snapshot(){if(typeof calcStats==='function')calcStats();let d=player.d||{},lv=Number(player.lv||1),atk=Math.max(Number(d.meleeDmg||0),Number(d.rangedDmg||0),Number(d.magicDmg||0))+Number(d.extraDmg||0)+lv*8,def=Math.max(0,-Number(d.ac||0))*2+Number(d.dr||0)*15+Number(d.mr||0)*.25,crit=Math.max(Number(d.meleeCrit||0),Number(d.rangedCrit||0),Number(d.magicCrit||0)),speed=1/Math.max(.4,Number(d.aspd||1));return{lv,class:player.cls||'冒險者',max_hp:Math.max(100,Number(player.mhp||player.hp||100)),atk:Math.round(atk),def:Math.round(def),crit:Math.round(crit*10)/10,speed:Math.round(speed*100)/100};}
function recordHtml(r={}){return `<div class="pvp-card" style="display:flex;justify-content:space-around;gap:8px;flex-wrap:wrap"><b>競技積分 ${Number(r.rating||1000)}</b><span>勝 ${Number(r.wins||0)}</span><span>敗 ${Number(r.losses||0)}</span><span>和 ${Number(r.draws||0)}</span></div>`;}
function renderIdle(s){body().innerHTML=`<div class="pvp-card"><h2 style="font-size:22px;color:#fdba74">真人連線自動 PK</h2><p>系統會尋找另一位正在排隊的玩家。配對後，雙方會看到同一份 HP、回合與戰報；戰鬥由伺服器計算直到分出勝負。</p><small style="color:#94a3b8">角色的 HP、攻擊、防禦、爆擊與攻速會轉換成競技場能力。勝利 +15 分，失敗 -10 分，平手 +2 分。</small></div>${recordHtml(s)}<div class="pvp-actions"><button onclick="pvpStart()">開始配對</button></div>`;}
function renderQueue(s){body().innerHTML=`${recordHtml(s)}<div class="pvp-card" style="text-align:center"><div style="font-size:46px">⚔</div><h2 style="font-size:22px;color:#fde68a">尋找對手中…</h2><p>${esc(s.message||'等待另一位玩家')}</p><small style="color:#94a3b8">請保持此視窗開啟，配對成功會自動進入戰鬥。</small></div><div class="pvp-actions"><button onclick="pvpCancel()">取消配對</button></div>`;}
function fighter(x,side,mine){let st=x.stats||{},hp=Number(x.hp||0),max=Number(st.max_hp||1),pct=Math.max(0,Math.min(100,hp/max*100));return `<div class="pvp-fighter ${mine===side?'mine':''}"><h3>${mine===side?'⭐ ':''}${esc(x.name)}</h3><small>${x.tag?'@'+esc(x.tag)+'｜':''}Lv.${st.lv||1} ${esc(st.class||'')}</small><div class="pvp-hp"><i style="width:${pct}%"></i></div><b>HP ${hp.toLocaleString()} / ${max.toLocaleString()}</b><small style="display:block;color:#94a3b8;margin-top:6px">攻擊 ${st.atk}｜防禦 ${st.def}｜爆擊 ${st.crit}%｜攻速 ${st.speed}</small></div>`;}
function renderMatch(s){let logs=(s.log||[]).slice(-14).reverse().map(x=>`<div><b style="color:#fde68a">第 ${x.round} 回合</b>　${esc(s.player1.name)} 造成 <span style="color:#fb923c">${Number(x.d1).toLocaleString()}</span>${x.c1?'（爆擊）':''}，${esc(s.player2.name)} 造成 <span style="color:#60a5fa">${Number(x.d2).toLocaleString()}</span>${x.c2?'（爆擊）':''}</div>`).join('');let done=s.status==='finished',won=s.winner_id&&s.winner_id===pu.id,draw=done&&!s.winner_id;body().innerHTML=`<div class="pvp-duel">${fighter(s.player1,1,s.my_side)}<div class="pvp-vs">VS<br><small>回合 ${s.round}</small></div>${fighter(s.player2,2,s.my_side)}</div>${done?`<div class="pvp-result" style="color:${draw?'#cbd5e1':won?'#86efac':'#fca5a5'}">${draw?'平手':won?'🏆 勝利':'戰敗'}<br><small>${esc(s.result_text||'戰鬥結束')}</small></div>`:'<div class="pvp-card" style="text-align:center;color:#93c5fd">雙方正在自動交戰，戰況由伺服器同步…</div>'}<div class="pvp-log">${logs||'<div>戰鬥即將開始…</div>'}</div>${done?recordHtml(s.record):''}<div class="pvp-actions">${done?'<button onclick="pvpStart()">再次配對</button>':'<button onclick="pvpForfeit()">投降</button>'}</div>`;}
function render(s){pState=s||{kind:'idle'};if(pState.kind==='queued')renderQueue(pState);else if(pState.kind==='match')renderMatch(pState);else renderIdle(pState);}
function schedule(){clearTimeout(pTimer);if(document.getElementById('pvp-panel')?.style.display!=='flex')return;if(pState.kind==='queued'||(pState.kind==='match'&&pState.status==='active'))pTimer=setTimeout(step,900);}
async function step(){if(pBusy)return schedule();pBusy=true;try{let r=pState.kind==='match'?await pc.rpc('pvp_tick',{p_match:pState.id}):await pc.rpc('pvp_poll');if(r.error)throw r.error;render(r.data);}catch(e){note(esc(e.message),'#fca5a5');}finally{pBusy=false;schedule();}}
window.pvpOpen=async()=>{let p=panel();p.style.display='flex';note('正在連線競技場…','#93c5fd');try{await init();let r=await pc.rpc('pvp_poll');if(r.error)throw r.error;render(r.data);schedule();}catch(e){note(`${esc(e.message)}<br><br>請先到 Supabase SQL Editor 執行 <b>supabase-pvp.sql</b>。`,'#fca5a5');}};
window.pvpClose=async()=>{clearTimeout(pTimer);if(pState.kind==='queued'&&pc)await pc.rpc('pvp_cancel_queue');let p=document.getElementById('pvp-panel');if(p)p.style.display='none';};
window.pvpStart=async()=>{if(pBusy)return;pBusy=true;note('正在加入配對…','#93c5fd');try{let r=await pc.rpc('pvp_join_queue',{p_snapshot:snapshot()});if(r.error)throw r.error;render(r.data);}catch(e){note(esc(e.message),'#fca5a5');}finally{pBusy=false;schedule();}};
window.pvpCancel=async()=>{clearTimeout(pTimer);let r=await pc.rpc('pvp_cancel_queue');if(r.error)return alert(r.error.message);pState={kind:'idle'};let s=await pc.rpc('pvp_poll');render(s.data);};
window.pvpForfeit=async()=>{if(!confirm('確定要投降並判定本場失敗嗎？'))return;let r=await pc.rpc('pvp_forfeit',{p_match:pState.id});if(r.error)return alert(r.error.message);render(r.data);};
})();
