/* Supabase 全服／血盟聊天室：共用交易所匿名登入，每 3 秒更新。 */
(function(){
'use strict';
let client=null,user=null,channel='global',ready=false,busy=false,lastSig='',playerTag='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const el=id=>document.getElementById(id);
function setStatus(t,color='#94a3b8'){const x=el('chat-status');if(x){x.textContent=t;x.style.color=color;}}
async function init(){if(ready)return true;if(!window.MARKET_CONFIG||!window.supabase?.createClient)return false;client=client||window.supabase.createClient(MARKET_CONFIG.url,MARKET_CONFIG.anonKey,{auth:{persistSession:true,autoRefreshToken:true}});let {data:{session}}=await client.auth.getSession();if(!session){const r=await client.auth.signInAnonymously();if(r.error)throw r.error;session=r.data.session;}user=session.user;const name=(window.player&&player.name)||'冒險者';const p=await client.rpc('market_ensure_profile',{p_name:name});if(p.error)throw p.error;const me=await client.rpc('player_my_identity');if(!me.error&&me.data){playerTag=me.data.player_tag||'';const b=el('chat-id-btn');if(b)b.textContent=playerTag?'@'+playerTag:'設定ID';}ready=true;setStatus(playerTag?`已連線｜@${playerTag}`:'已連線｜尚未設定玩家ID',playerTag?'#86efac':'#fbbf24');return true;}
async function read(){if(document.hidden||!el('chat-panel')||el('game-screen')?.classList.contains('hidden'))return;try{if(!await init())return;const r=await client.rpc('chat_read',{p_channel:channel});if(r.error)throw r.error;const rows=r.data||[],sig=rows.map(x=>x.id).join(',');if(sig===lastSig)return;lastSig=sig;const box=el('chat-messages'),wasBottom=box.scrollHeight-box.scrollTop-box.clientHeight<40;box.innerHTML=rows.map(m=>`<div style="line-height:1.35;word-break:break-word"><span style="color:#64748b">${new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span> <b style="color:${channel==='clan'?'#fdba74':'#7dd3fc'}">${esc(m.author)}</b>：<span style="color:#e2e8f0">${esc(m.content)}</span></div>`).join('')||'<div style="color:#64748b;text-align:center;padding:20px">目前還沒有訊息。</div>';if(wasBottom||!box.dataset.seen){box.scrollTop=box.scrollHeight;box.dataset.seen='1';}}catch(e){setStatus(e.message.includes('chat_read')?'請先執行 supabase-chat.sql':e.message,'#fca5a5');}}
window.chatSwitch=function(k){channel=k;lastSig='';el('chat-tab-global')?.classList.toggle('active',k==='global');el('chat-tab-clan')?.classList.toggle('active',k==='clan');setStatus(k==='global'?'全服頻道':'血盟專屬頻道',k==='global'?'#7dd3fc':'#fdba74');read();};
window.chatSend=async function(){const input=el('chat-input'),content=input?.value.trim();if(!content||busy)return;busy=true;try{if(!await init())throw new Error('聊天室尚未連線');const r=await client.rpc('chat_send',{p_channel:channel,p_content:content});if(r.error)throw r.error;input.value='';lastSig='';await read();}catch(e){alert('發送失敗：'+e.message);}finally{busy=false;}};
window.chatSetId=async function(){try{await init();const v=prompt('設定唯一玩家ID（2～16位中文、英文字母、數字或底線）',playerTag||'');if(v==null)return;const tag=v.trim();if(!/^[\p{L}\p{N}_]{2,16}$/u.test(tag))return alert('ID格式錯誤：只能使用2～16位中文、英文字母、數字或底線。');const r=await client.rpc('player_set_tag',{p_tag:tag});if(r.error)throw r.error;playerTag=tag;el('chat-id-btn').textContent='@'+tag;setStatus(`已連線｜@${tag}`,'#86efac');alert('玩家ID設定完成：@'+tag);}catch(e){alert('設定失敗：'+e.message);}};
setInterval(read,3000);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{chatSwitch('global');read();});else{chatSwitch('global');read();}
})();
