-- 線上血盟完整擴充：請先執行 supabase-clan.sql，再執行本檔。
alter table public.clan_members add column if not exists coins bigint not null default 0 check(coins>=0);
alter table public.clan_members drop constraint if exists clan_members_role_check;
alter table public.clan_members add constraint clan_members_role_check check(role in('owner','officer','guardian','elite','member'));

create table if not exists public.clan_checkins(user_id uuid not null references auth.users(id) on delete cascade,clan_id uuid not null references clans(id) on delete cascade,checked_on date not null default current_date,primary key(user_id,checked_on));
create table if not exists public.clan_shop_purchases(user_id uuid not null references auth.users(id) on delete cascade,item_key text not null,bought_on date not null default current_date,primary key(user_id,item_key,bought_on));
create table if not exists public.clan_boss_damage(clan_id uuid not null references clans(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,week_start date not null,damage bigint not null default 0,attacks integer not null default 0,primary key(clan_id,user_id,week_start));
create table if not exists public.clan_tech(clan_id uuid not null references clans(id) on delete cascade,tech_key text not null,level integer not null default 0 check(level between 0 and 10),primary key(clan_id,tech_key));
create table if not exists public.clan_storage(id uuid primary key default gen_random_uuid(),clan_id uuid not null references clans(id) on delete cascade,item_name text not null,item_data jsonb not null,qty integer not null check(qty>0),depositor_id uuid not null references auth.users(id),created_at timestamptz not null default now());
create table if not exists public.clan_storage_logs(id bigint generated always as identity primary key,clan_id uuid not null references clans(id) on delete cascade,user_id uuid not null references auth.users(id),action text not null,item_name text not null,qty integer not null,created_at timestamptz not null default now());
create table if not exists public.clan_posts(id uuid primary key default gen_random_uuid(),clan_id uuid not null references clans(id) on delete cascade,author_id uuid not null references auth.users(id),content text not null check(char_length(content) between 1 and 300),pinned boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.clan_mission_claims(clan_id uuid not null references clans(id) on delete cascade,mission_key text not null,period_start date not null,claimed_by uuid not null references auth.users(id),claimed_at timestamptz not null default now(),primary key(clan_id,mission_key,period_start));
alter table clan_checkins enable row level security;alter table clan_shop_purchases enable row level security;alter table clan_boss_damage enable row level security;alter table clan_tech enable row level security;alter table clan_storage enable row level security;alter table clan_storage_logs enable row level security;alter table clan_posts enable row level security;

create or replace function public.clan_checkin() returns jsonb language plpgsql security definer set search_path=public as $$
declare cid uuid; n integer;
begin select clan_id into cid from clan_members where user_id=auth.uid();if cid is null then raise exception '尚未加入血盟';end if;insert into clan_checkins(user_id,clan_id) values(auth.uid(),cid);update clan_members set coins=coins+10,contribution=contribution+5 where user_id=auth.uid();update clans set xp=xp+10,funds=funds+10000 where id=cid;perform clan_raise_level(cid);select count(*) into n from clan_checkins where clan_id=cid and checked_on=current_date;return jsonb_build_object('coins',10,'count',n);
exception when unique_violation then raise exception '今天已經簽到';end $$;

create or replace function public.clan_shop_buy(p_item text) returns jsonb language plpgsql security definer set search_path=public as $$
declare cost integer;qty integer;reward text;
begin select x.c,x.q,x.r into cost,qty,reward from (values('ore',20,5,'ore'),('rune',15,10,'runeDust'),('food',15,10,'petFood'),('sweep',25,2,'sweep'),('shelin',40,1,'shelinPotion'))x(k,c,q,r) where x.k=p_item;if cost is null then raise exception '商品不存在';end if;insert into clan_shop_purchases(user_id,item_key) values(auth.uid(),p_item);update clan_members set coins=coins-cost where user_id=auth.uid() and coins>=cost;if not found then raise exception '血盟幣不足';end if;return jsonb_build_object('reward',reward,'qty',qty,'cost',cost);
exception when unique_violation then raise exception '今天已購買此商品';end $$;

create or replace function public.clan_boss_attack(p_damage bigint) returns jsonb language plpgsql security definer set search_path=public as $$
declare cid uuid;wk date;d bigint;total bigint;
begin select clan_id into cid from clan_members where user_id=auth.uid();if cid is null then raise exception '尚未加入血盟';end if;wk:=date_trunc('week',current_date)::date;d:=greatest(1,least(p_damage,10000000));insert into clan_boss_damage values(cid,auth.uid(),wk,d,1) on conflict(clan_id,user_id,week_start) do update set damage=clan_boss_damage.damage+excluded.damage,attacks=clan_boss_damage.attacks+1 where clan_boss_damage.attacks<3;if not found then raise exception '本週攻擊次數已用完';end if;update clan_members set coins=coins+5,contribution=contribution+2 where user_id=auth.uid();select sum(damage) into total from clan_boss_damage where clan_id=cid and week_start=wk;return jsonb_build_object('damage',d,'total',total,'hp',100000000);
end $$;

create or replace function public.clan_tech_upgrade(p_tech text) returns void language plpgsql security definer set search_path=public as $$
declare cid uuid;lv integer;cost bigint;
begin select clan_id into cid from clan_members where user_id=auth.uid() and role in('owner','officer');if cid is null then raise exception '沒有升級權限';end if;if p_tech not in('hp','damage','gold','boss') then raise exception '科技不存在';end if;insert into clan_tech values(cid,p_tech,0) on conflict do nothing;select level into lv from clan_tech where clan_id=cid and tech_key=p_tech for update;if lv>=10 then raise exception '已達最高等級';end if;cost:=(lv+1)*100000;update clans set funds=funds-cost where id=cid and funds>=cost;if not found then raise exception '血盟資金不足';end if;update clan_tech set level=level+1 where clan_id=cid and tech_key=p_tech;end $$;

create or replace function public.clan_storage_deposit(p_name text,p_data jsonb,p_qty integer) returns uuid language plpgsql security definer set search_path=public as $$
declare cid uuid;sid uuid;begin select clan_id into cid from clan_members where user_id=auth.uid();if cid is null or p_qty<1 then raise exception '資料不正確';end if;insert into clan_storage(clan_id,item_name,item_data,qty,depositor_id) values(cid,left(p_name,100),p_data,p_qty,auth.uid()) returning id into sid;insert into clan_storage_logs(clan_id,user_id,action,item_name,qty) values(cid,auth.uid(),'deposit',left(p_name,100),p_qty);return sid;end $$;
create or replace function public.clan_storage_withdraw(p_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$
declare cid uuid;s clan_storage;begin select clan_id into cid from clan_members where user_id=auth.uid() and role in('owner','officer','guardian');if cid is null then raise exception '只有盟主、副盟主與守護騎士可以領取';end if;delete from clan_storage where id=p_id and clan_id=cid returning * into s;if s.id is null then raise exception '物品不存在';end if;insert into clan_storage_logs(clan_id,user_id,action,item_name,qty) values(cid,auth.uid(),'withdraw',s.item_name,s.qty);return jsonb_build_object('item',s.item_data,'qty',s.qty);end $$;

create or replace function public.clan_set_role(p_user uuid,p_role text) returns void language plpgsql security definer set search_path=public as $$
declare cid uuid;begin select clan_id into cid from clan_members where user_id=auth.uid() and role='owner';if cid is null then raise exception '只有盟主可以調整職位';end if;if p_role not in('officer','guardian','elite','member') then raise exception '職位不正確';end if;update clan_members set role=p_role where clan_id=cid and user_id=p_user and role<>'owner';end $$;
create or replace function public.clan_post(p_content text) returns uuid language plpgsql security definer set search_path=public as $$
declare cid uuid;pid uuid;begin select clan_id into cid from clan_members where user_id=auth.uid();if cid is null or char_length(trim(p_content)) not between 1 and 300 then raise exception '留言內容不正確';end if;insert into clan_posts(clan_id,author_id,content) values(cid,auth.uid(),trim(p_content)) returning id into pid;return pid;end $$;

create or replace function public.clan_claim_mission(p_mission text) returns void language plpgsql security definer set search_path=public as $$
declare cid uuid;period date;progress bigint;need bigint;
begin select clan_id into cid from clan_members where user_id=auth.uid();if cid is null then raise exception '尚未加入血盟';end if;
 if p_mission='checkin' then period:=current_date;need:=3;select count(*) into progress from clan_checkins where clan_id=cid and checked_on=current_date;
 elsif p_mission='boss' then period:=date_trunc('week',current_date)::date;need:=1000000;select coalesce(sum(damage),0) into progress from clan_boss_damage where clan_id=cid and week_start=period;
 elsif p_mission='donate' then period:=current_date;need:=500000;select coalesce(sum(d.amount),0) into progress from clan_donations d join clan_members m on m.user_id=d.user_id where m.clan_id=cid and d.donated_on=current_date;
 else raise exception '任務不存在';end if;if progress<need then raise exception '任務尚未完成';end if;
 insert into clan_mission_claims values(cid,p_mission,period,auth.uid(),now());update clans set funds=funds+100000,xp=xp+50 where id=cid;update clan_members set coins=coins+10 where clan_id=cid;perform clan_raise_level(cid);
exception when unique_violation then raise exception '本期獎勵已領取';end $$;

create or replace function public.clan_leaderboard() returns table(rank bigint,id uuid,name text,level integer,members bigint,power bigint) language sql security definer set search_path=public as $$select row_number()over(order by c.level desc,c.xp desc,c.funds desc),c.id,c.name,c.level,count(m.user_id),c.level*100000+c.xp+c.funds/100 from clans c left join clan_members m on m.clan_id=c.id group by c.id order by c.level desc,c.xp desc,c.funds desc limit 50$$;
create or replace function public.clan_war_state() returns jsonb language plpgsql security definer set search_path=public as $$
declare cid uuid;my_score bigint;opp record;begin select clan_id into cid from clan_members where user_id=auth.uid();if cid is null then raise exception '尚未加入血盟';end if;select coalesce(sum(damage),0) into my_score from clan_boss_damage where clan_id=cid and week_start=date_trunc('week',current_date)::date;select c.id,c.name,coalesce(sum(d.damage),0) score into opp from clans c left join clan_boss_damage d on d.clan_id=c.id and d.week_start=date_trunc('week',current_date)::date where c.id<>cid group by c.id order by abs(coalesce(sum(d.damage),0)-my_score) limit 1;return jsonb_build_object('my_score',my_score,'opponent_id',opp.id,'opponent_name',opp.name,'opponent_score',coalesce(opp.score,0));end $$;

create or replace function public.clan_expansion_state() returns jsonb language plpgsql security definer set search_path=public as $$
declare cid uuid;mine clan_members;wk date;begin select * into mine from clan_members where user_id=auth.uid();cid:=mine.clan_id;wk:=date_trunc('week',current_date)::date;if cid is null then return '{}'::jsonb;end if;return jsonb_build_object('coins',mine.coins,'checked',exists(select 1 from clan_checkins where user_id=auth.uid() and checked_on=current_date),'checkins',(select count(*) from clan_checkins where clan_id=cid and checked_on=current_date),'donations_today',coalesce((select sum(d.amount) from clan_donations d join clan_members m on m.user_id=d.user_id where m.clan_id=cid and d.donated_on=current_date),0),'mission_claims',coalesce((select jsonb_agg(mission_key) from clan_mission_claims where clan_id=cid and(period_start=current_date or period_start=wk)),'[]'::jsonb),'tech',coalesce((select jsonb_object_agg(tech_key,level) from clan_tech where clan_id=cid),'{}'::jsonb),'boss_total',coalesce((select sum(damage) from clan_boss_damage where clan_id=cid and week_start=wk),0),'boss_mine',coalesce((select damage from clan_boss_damage where clan_id=cid and user_id=auth.uid() and week_start=wk),0),'boss_attacks',coalesce((select attacks from clan_boss_damage where clan_id=cid and user_id=auth.uid() and week_start=wk),0),'storage',coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'item_name',s.item_name,'item_data',s.item_data,'qty',s.qty,'depositor',coalesce(p.display_name,'冒險者'),'created_at',s.created_at)order by s.created_at desc)from clan_storage s left join market_profiles p on p.user_id=s.depositor_id where s.clan_id=cid),'[]'::jsonb),'posts',coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'author',coalesce(p.display_name,'冒險者'),'content',x.content,'pinned',x.pinned,'created_at',x.created_at)order by x.pinned desc,x.created_at desc)from(select * from clan_posts where clan_id=cid order by created_at desc limit 50)x left join market_profiles p on p.user_id=x.author_id),'[]'::jsonb));end $$;

revoke all on function clan_checkin(),clan_shop_buy(text),clan_boss_attack(bigint),clan_tech_upgrade(text),clan_storage_deposit(text,jsonb,integer),clan_storage_withdraw(uuid),clan_set_role(uuid,text),clan_post(text),clan_claim_mission(text),clan_leaderboard(),clan_war_state(),clan_expansion_state() from public;
grant execute on function clan_checkin(),clan_shop_buy(text),clan_boss_attack(bigint),clan_tech_upgrade(text),clan_storage_deposit(text,jsonb,integer),clan_storage_withdraw(uuid),clan_set_role(uuid,text),clan_post(text),clan_claim_mission(text),clan_leaderboard(),clan_war_state(),clan_expansion_state() to authenticated;
notify pgrst,'reload schema';
